Enhance Jenkinsfile with parameters and updates
Added parameters for AMI ID and AWS credentials to the Jenkins pipeline. Updated the git repository URL and modified the terraform steps to use the new parameters.

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,19 +1,26 @@
 pipeline{
     agent any
+    parameters {
+        string(name: 'AMI_ID', defaultValue: 'ami-073130f74f5ffb161', description: 'Amazon Machine Image (AMI) ID to use for the EC2 instance')
+        string(name: 'AWS_CREDENTIALS_ID', defaultValue: 'aws-jenkins-creds', description: 'Jenkins AWS credentials ID')
+    }
     stages {
         stage('source code') {
             steps {
                 echo 'Cloning...'
-                   git branch: 'main', url: 'https://github.com/Subxsh/day6.git'
+                   git branch: 'main', url: 'https://github.com/PV-Sudarsan/task-jenkins.git'
 
             }
         }
         stage('terraform') {
             steps {
                 echo 'Deploying...'
-                sh 'terraform init'
-                sh 'terraform plan -var="ami_id=ami-073130f74f5ffb161"'
-                sh 'terraform apply -var="ami_id=ami-073130f74f5ffb161" -auto-approve'
+                sh '[ -n "${AMI_ID}" ] || (echo "AMI_ID is required" && exit 1)'
+                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: params.AWS_CREDENTIALS_ID]]) {
+                    sh 'terraform init'
+                    sh "terraform plan -var=\"ami_id=${params.AMI_ID}\""
+                    sh "terraform apply -var=\"ami_id=${params.AMI_ID}\" -auto-approve"
+                }
             }
         }
     }
