Refactor Jenkinsfile for improved readability
Refactor Jenkins pipeline to improve readability and structure.

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,25 +1,39 @@
-pipeline{
+pipeline {
     agent any
-    parameters {
-        string(name: 'AMI_ID', defaultValue: 'ami-073130f74f5ffb161', description: 'Amazon Machine Image (AMI) ID to use for the EC2 instance')
-        string(name: 'AWS_CREDENTIALS_ID', defaultValue: 'aws-jenkins-creds', description: 'Jenkins AWS credentials ID')
-    }
-    stages {
-        stage('source code') {
-            steps {
-                echo 'Cloning...'
-                   git branch: 'main', url: 'https://github.com/PV-Sudarsan/task-jenkins.git'
 
-            }
-        }
-        stage('terraform') {
+    parameters {
+        string(
+            name: 'AMI_ID',
+            defaultValue: 'ami-073130f74f5ffb161',
+            description: 'Amazon Machine Image (AMI) ID to use for the EC2 instance'
+        )
+        string(
+            name: 'AWS_CREDENTIALS_ID',
+            defaultValue: 'aws-jenkins-creds',
+            description: 'Jenkins AWS credentials ID'
+        )
+    }
+
+    stages {
+        stage('Terraform Deploy') {
             steps {
                 echo 'Deploying...'
-                sh '[ -n "${AMI_ID}" ] || (echo "AMI_ID is required" && exit 1)'
-                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: params.AWS_CREDENTIALS_ID]]) {
+
+                // Validate AMI_ID
+                sh '''
+                    if [ -z "$AMI_ID" ]; then
+                        echo "AMI_ID is required"
+                        exit 1
+                    fi
+                '''
+
+                withCredentials([
+                    [$class: 'AmazonWebServicesCredentialsBinding',
+                     credentialsId: params.AWS_CREDENTIALS_ID]
+                ]) {
                     sh 'terraform init'
-                    sh "terraform plan -var=\"ami_id=${params.AMI_ID}\""
-                    sh "terraform apply -var=\"ami_id=${params.AMI_ID}\" -auto-approve"
+                    sh "terraform plan -var=\"ami_id=${AMI_ID}\""
+                    sh "terraform apply -var=\"ami_id=${AMI_ID}\" -auto-approve"
                 }
             }
         }
